################################################################################
Concuerror started with options:
  [{'after-timeout',infinite},
   {bound,-1},
   {distributed,true},
   {files,["/home/stavros/git/Concuerror/tests/suites/basic_tests/src/after_vs_trap_exit.erl"]},
   {'light-dpor',false},
   {symbolic,true},
   {target,{after_vs_trap_exit,after_vs_trap_exit,[]}},
   {verbose,0},
   {wait,5000}]
################################################################################
Erroneous interleaving 1:
* Blocked at a 'receive' (when all other processes have exited):
    P.1 in after_vs_trap_exit.erl line 14
--------------------------------------------------------------------------------
Interleaving info:
   1: P: P.1 = erlang:spawn_link(erlang, apply, [#Fun<after_vs_trap_exit.0.114045005>,[]])
    in erlang.erl line 2209
   2: P.1: false = erlang:process_flag(trap_exit, true)
   3: P.1: ok = P ! ok
    in after_vs_trap_exit.erl line 13
   4: Message (ok) from P.1 reaches P
   5: P: receives message (ok)
    in after_vs_trap_exit.erl line 16
   6: P: P.2 = erlang:spawn(erlang, apply, [#Fun<after_vs_trap_exit.2.114045005>,[]])
    in erlang.erl line 2188
   7: P: true = erlang:link(P.2)
    in after_vs_trap_exit.erl line 27
   8: P: exits normally
   9: P: true = erlang:exit(P.1, normal)
    (while exiting)
  10: Exit signal (normal) from P reaches P.1
  11: P: true = erlang:exit(P.2, normal)
    (while exiting)
  12: Exit signal (normal) from P reaches P.2
  13: P.2: false = erlang:process_flag(trap_exit, true)
    in after_vs_trap_exit.erl line 20
  14: P.2: receive timeout expired after 0 ms
    in after_vs_trap_exit.erl line 21
  15: P.2: exits normally
  16: P.2: true = erlang:exit(P, normal)
    (while exiting)
  17: Exit signal (normal) from P.2 reaches P
################################################################################
Erroneous interleaving 2:
* Blocked at a 'receive' (when all other processes have exited):
    P.1 in after_vs_trap_exit.erl line 14
* At step 15 process P.2 exited abnormally
    Reason:
      {{nocatch,{'EXIT',P,normal}},
       [{after_vs_trap_exit,'-after_vs_trap_exit/0-fun-1-',0,
                            [{file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/after_vs_trap_exit.erl"},
                             {line,22}]}]}
    Stacktrace:
      [{after_vs_trap_exit,'-after_vs_trap_exit/0-fun-1-',0,
                           [{file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/after_vs_trap_exit.erl"},
                            {line,22}]}]
--------------------------------------------------------------------------------
Interleaving info:
   1: P: P.1 = erlang:spawn_link(erlang, apply, [#Fun<after_vs_trap_exit.0.114045005>,[]])
    in erlang.erl line 2209
   2: P.1: false = erlang:process_flag(trap_exit, true)
   3: P.1: ok = P ! ok
    in after_vs_trap_exit.erl line 13
   4: Message (ok) from P.1 reaches P
   5: P: receives message (ok)
    in after_vs_trap_exit.erl line 16
   6: P: P.2 = erlang:spawn(erlang, apply, [#Fun<after_vs_trap_exit.2.114045005>,[]])
    in erlang.erl line 2188
   7: P: true = erlang:link(P.2)
    in after_vs_trap_exit.erl line 27
   8: P: exits normally
   9: P: true = erlang:exit(P.1, normal)
    (while exiting)
  10: Exit signal (normal) from P reaches P.1
  11: P: true = erlang:exit(P.2, normal)
    (while exiting)
  12: P.2: false = erlang:process_flag(trap_exit, true)
    in after_vs_trap_exit.erl line 20
  13: Exit signal (normal) from P reaches P.2
  14: P.2: receives message ({'EXIT',P,normal})
    in after_vs_trap_exit.erl line 21
  15: P.2: exits abnormally ({{nocatch,{'EXIT',P,normal}},[{after_vs_trap_exit,'-after_vs_trap_exit/0-fun-1-',0,[{file,[47,104,111,109,101,47,115,116,97,118,114,111,115,47,103,105,116,47,67,111,110,99,117,101,114,114,111,114,47,116,101,115,116,115,47,115,117,105,116,101,115,47,98,97,115,105,99,95,116,101,115,116,115,47,115,114,99,47,97,102,116,101,114,95,118,115,95,116,114,97,112,95,101,120,105,116,46,101,114,108]},{line,22}]}]})
  16: P.2: true = erlang:exit(P, {{nocatch,{'EXIT',P,normal}},[{after_vs_trap_exit,'-after_vs_trap_exit/0-fun-1-',0,[{file,[47,104,111,109,101,47,115,116,97,118,114,111,115,47,103,105,116,47,67,111,110,99,117,101,114,114,111,114,47,116,101,115,116,115,47,115,117,105,116,101,115,47,98,97,115,105,99,95,116,101,115,116,115,47,115,114,99,47,97,102,116,101,114,95,118,115,95,116,114,97,112,95,101,120,105,116,46,101,114,108]},{line,22}]}]})
    (while exiting)
  17: Exit signal ({{nocatch,{'EXIT',P,normal}},[{after_vs_trap_exit,'-after_vs_trap_exit/0-fun-1-',0,[{file,[47,104,111,109,101,47,115,116,97,118,114,111,115,47,103,105,116,47,67,111,110,99,117,101,114,114,111,114,47,116,101,115,116,115,47,115,117,105,116,101,115,47,98,97,115,105,99,95,116,101,115,116,115,47,115,114,99,47,97,102,116,101,114,95,118,115,95,116,114,97,112,95,101,120,105,116,46,101,114,108]},{line,22}]}]}) from P.2 reaches P
################################################################################
Erroneous interleaving 3:
* Blocked at a 'receive' (when all other processes have exited):
    P.1 in after_vs_trap_exit.erl line 14
--------------------------------------------------------------------------------
Interleaving info:
   1: P: P.1 = erlang:spawn_link(erlang, apply, [#Fun<after_vs_trap_exit.0.114045005>,[]])
    in erlang.erl line 2209
   2: P.1: false = erlang:process_flag(trap_exit, true)
   3: P.1: ok = P ! ok
    in after_vs_trap_exit.erl line 13
   4: Message (ok) from P.1 reaches P
   5: P: receives message (ok)
    in after_vs_trap_exit.erl line 16
   6: P: P.2 = erlang:spawn(erlang, apply, [#Fun<after_vs_trap_exit.2.114045005>,[]])
    in erlang.erl line 2188
   7: P: true = erlang:link(P.2)
    in after_vs_trap_exit.erl line 27
   8: P: exits normally
   9: P: true = erlang:exit(P.1, normal)
    (while exiting)
  10: Exit signal (normal) from P reaches P.1
  11: P: true = erlang:exit(P.2, normal)
    (while exiting)
  12: P.2: false = erlang:process_flag(trap_exit, true)
    in after_vs_trap_exit.erl line 20
  13: P.2: receive timeout expired after 0 ms
    in after_vs_trap_exit.erl line 21
  14: Exit signal (normal) from P reaches P.2
  15: P.2: exits normally
  16: P.2: true = erlang:exit(P, normal)
    (while exiting)
  17: Exit signal (normal) from P.2 reaches P
################################################################################
Erroneous interleaving 4:
* Blocked at a 'receive' (when all other processes have exited):
    P.1 in after_vs_trap_exit.erl line 14
--------------------------------------------------------------------------------
Interleaving info:
   1: P: P.1 = erlang:spawn_link(erlang, apply, [#Fun<after_vs_trap_exit.0.114045005>,[]])
    in erlang.erl line 2209
   2: P.1: false = erlang:process_flag(trap_exit, true)
   3: P.1: ok = P ! ok
    in after_vs_trap_exit.erl line 13
   4: Message (ok) from P.1 reaches P
   5: P: receives message (ok)
    in after_vs_trap_exit.erl line 16
   6: P: P.2 = erlang:spawn(erlang, apply, [#Fun<after_vs_trap_exit.2.114045005>,[]])
    in erlang.erl line 2188
   7: P.2: false = erlang:process_flag(trap_exit, true)
    in after_vs_trap_exit.erl line 20
   8: P.2: receive timeout expired after 0 ms
    in after_vs_trap_exit.erl line 21
   9: P.2: exits normally
  10: P: Exception noproc raised by: erlang:link(P.2)
    in after_vs_trap_exit.erl line 27
  11: P: exits normally
  12: P: true = erlang:exit(P.1, normal)
    (while exiting)
  13: Exit signal (normal) from P reaches P.1
################################################################################
Done! (Exit status: completed)
  Summary: 4 errors, 4/4 interleavings explored
