Concuerror 0.17 (d20441c) started at 24 Nov 2016 14:18:13.
 Options:
  [{after_timeout,infinity},
   {assertions_only,false},
   {assume_racing,false},
   {depth_bound,500},
   {disable_sleep_sets,false},
   {dpor,optimal},
   {entry_point,{ets_unnamed,test3,[]}},
   {files,["/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"]},
   {ignore_error,[]},
   {instant_delivery,true},
   {interleaving_bound,infinity},
   {keep_going,true},
   {non_racing_system,[]},
   {print_depth,20},
   {scheduling,round_robin},
   {scheduling_bound_type,none},
   {show_races,false},
   {strict_scheduling,false},
   {symbolic_names,true},
   {timeout,infinity},
   {treat_as_normal,[]}]
################################################################################
Interleaving #2
--------------------------------------------------------------------------------
Errors found:
* At step 19 process P.3 exited abnormally
    Reason:
      {badarg,[{erlang,register,
                       [tabler,P.3],
                       [32,
                        {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]}
    Stacktrace:
      [{erlang,register,
               [tabler,P.3],
               [32,
                {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]
--------------------------------------------------------------------------------
Event trace:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   3: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   4: P: exits normally
   5: P.1: 2 = ets:new(table, [private])
    in ets_unnamed.erl line 29
   6: P.1: true = ets:insert(2, {1,2})
    in ets_unnamed.erl line 30
   7: P.1: true = ets:insert(2, {1,3})
    in ets_unnamed.erl line 31
   8: P.1: true = erlang:register(tabler, P.1)
    in ets_unnamed.erl line 32
   9: P.1: exits normally
  10: P.1: true = ets:delete(2)
    (while exiting)
  11: P.2: 3 = ets:new(table, [private])
    in ets_unnamed.erl line 29
  12: P.2: true = ets:insert(3, {1,2})
    in ets_unnamed.erl line 30
  13: P.2: true = ets:insert(3, {1,3})
    in ets_unnamed.erl line 31
  14: P.2: true = erlang:register(tabler, P.2)
    in ets_unnamed.erl line 32
  15: P.3: 4 = ets:new(table, [private])
    in ets_unnamed.erl line 29
  16: P.3: true = ets:insert(4, {1,2})
    in ets_unnamed.erl line 30
  17: P.3: true = ets:insert(4, {1,3})
    in ets_unnamed.erl line 31
  18: P.3: Exception badarg raised by: erlang:register(tabler, P.3)
    in ets_unnamed.erl line 32
  19: P.3: exits abnormally ({badarg,[{erlang,register,[tabler,P.3],[32,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  20: P.3: true = ets:delete(4)
    (while exiting)
  21: P.2: exits normally
  22: P.2: true = ets:delete(3)
    (while exiting)
################################################################################
Interleaving #4
--------------------------------------------------------------------------------
Errors found:
* At step 19 process P.2 exited abnormally
    Reason:
      {badarg,[{erlang,register,
                       [tabler,P.2],
                       [32,
                        {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]}
    Stacktrace:
      [{erlang,register,
               [tabler,P.2],
               [32,
                {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]
--------------------------------------------------------------------------------
Event trace:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   3: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   4: P: exits normally
   5: P.1: 2 = ets:new(table, [private])
    in ets_unnamed.erl line 29
   6: P.1: true = ets:insert(2, {1,2})
    in ets_unnamed.erl line 30
   7: P.1: true = ets:insert(2, {1,3})
    in ets_unnamed.erl line 31
   8: P.1: true = erlang:register(tabler, P.1)
    in ets_unnamed.erl line 32
   9: P.1: exits normally
  10: P.1: true = ets:delete(2)
    (while exiting)
  11: P.2: 3 = ets:new(table, [private])
    in ets_unnamed.erl line 29
  12: P.2: true = ets:insert(3, {1,2})
    in ets_unnamed.erl line 30
  13: P.2: true = ets:insert(3, {1,3})
    in ets_unnamed.erl line 31
  14: P.3: 4 = ets:new(table, [private])
    in ets_unnamed.erl line 29
  15: P.3: true = ets:insert(4, {1,2})
    in ets_unnamed.erl line 30
  16: P.3: true = ets:insert(4, {1,3})
    in ets_unnamed.erl line 31
  17: P.3: true = erlang:register(tabler, P.3)
    in ets_unnamed.erl line 32
  18: P.2: Exception badarg raised by: erlang:register(tabler, P.2)
    in ets_unnamed.erl line 32
  19: P.2: exits abnormally ({badarg,[{erlang,register,[tabler,P.2],[32,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  20: P.2: true = ets:delete(3)
    (while exiting)
  21: P.3: exits normally
  22: P.3: true = ets:delete(4)
    (while exiting)
################################################################################
Interleaving #5
--------------------------------------------------------------------------------
Errors found:
* At step 16 process P.2 exited abnormally
    Reason:
      {badarg,[{erlang,register,
                       [tabler,P.2],
                       [32,
                        {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]}
    Stacktrace:
      [{erlang,register,
               [tabler,P.2],
               [32,
                {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]
* At step 19 process P.3 exited abnormally
    Reason:
      {badarg,[{erlang,register,
                       [tabler,P.3],
                       [32,
                        {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]}
    Stacktrace:
      [{erlang,register,
               [tabler,P.3],
               [32,
                {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]
--------------------------------------------------------------------------------
Event trace:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   3: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   4: P: exits normally
   5: P.1: 2 = ets:new(table, [private])
    in ets_unnamed.erl line 29
   6: P.1: true = ets:insert(2, {1,2})
    in ets_unnamed.erl line 30
   7: P.1: true = ets:insert(2, {1,3})
    in ets_unnamed.erl line 31
   8: P.1: true = erlang:register(tabler, P.1)
    in ets_unnamed.erl line 32
   9: P.2: 3 = ets:new(table, [private])
    in ets_unnamed.erl line 29
  10: P.2: true = ets:insert(3, {1,2})
    in ets_unnamed.erl line 30
  11: P.2: true = ets:insert(3, {1,3})
    in ets_unnamed.erl line 31
  12: P.3: 4 = ets:new(table, [private])
    in ets_unnamed.erl line 29
  13: P.3: true = ets:insert(4, {1,2})
    in ets_unnamed.erl line 30
  14: P.3: true = ets:insert(4, {1,3})
    in ets_unnamed.erl line 31
  15: P.2: Exception badarg raised by: erlang:register(tabler, P.2)
    in ets_unnamed.erl line 32
  16: P.2: exits abnormally ({badarg,[{erlang,register,[tabler,P.2],[32,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  17: P.2: true = ets:delete(3)
    (while exiting)
  18: P.3: Exception badarg raised by: erlang:register(tabler, P.3)
    in ets_unnamed.erl line 32
  19: P.3: exits abnormally ({badarg,[{erlang,register,[tabler,P.3],[32,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  20: P.3: true = ets:delete(4)
    (while exiting)
  21: P.1: exits normally
  22: P.1: true = ets:delete(2)
    (while exiting)
################################################################################
Interleaving #6
--------------------------------------------------------------------------------
Errors found:
* At step 16 process P.2 exited abnormally
    Reason:
      {badarg,[{erlang,register,
                       [tabler,P.2],
                       [32,
                        {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]}
    Stacktrace:
      [{erlang,register,
               [tabler,P.2],
               [32,
                {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]
--------------------------------------------------------------------------------
Event trace:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   3: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   4: P: exits normally
   5: P.1: 2 = ets:new(table, [private])
    in ets_unnamed.erl line 29
   6: P.1: true = ets:insert(2, {1,2})
    in ets_unnamed.erl line 30
   7: P.1: true = ets:insert(2, {1,3})
    in ets_unnamed.erl line 31
   8: P.1: true = erlang:register(tabler, P.1)
    in ets_unnamed.erl line 32
   9: P.2: 3 = ets:new(table, [private])
    in ets_unnamed.erl line 29
  10: P.2: true = ets:insert(3, {1,2})
    in ets_unnamed.erl line 30
  11: P.2: true = ets:insert(3, {1,3})
    in ets_unnamed.erl line 31
  12: P.3: 4 = ets:new(table, [private])
    in ets_unnamed.erl line 29
  13: P.3: true = ets:insert(4, {1,2})
    in ets_unnamed.erl line 30
  14: P.3: true = ets:insert(4, {1,3})
    in ets_unnamed.erl line 31
  15: P.2: Exception badarg raised by: erlang:register(tabler, P.2)
    in ets_unnamed.erl line 32
  16: P.2: exits abnormally ({badarg,[{erlang,register,[tabler,P.2],[32,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  17: P.2: true = ets:delete(3)
    (while exiting)
  18: P.1: exits normally
  19: P.1: true = ets:delete(2)
    (while exiting)
  20: P.3: true = erlang:register(tabler, P.3)
    in ets_unnamed.erl line 32
  21: P.3: exits normally
  22: P.3: true = ets:delete(4)
    (while exiting)
################################################################################
Interleaving #7
--------------------------------------------------------------------------------
Errors found:
* At step 16 process P.3 exited abnormally
    Reason:
      {badarg,[{erlang,register,
                       [tabler,P.3],
                       [32,
                        {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]}
    Stacktrace:
      [{erlang,register,
               [tabler,P.3],
               [32,
                {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]
--------------------------------------------------------------------------------
Event trace:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   3: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   4: P: exits normally
   5: P.1: 2 = ets:new(table, [private])
    in ets_unnamed.erl line 29
   6: P.1: true = ets:insert(2, {1,2})
    in ets_unnamed.erl line 30
   7: P.1: true = ets:insert(2, {1,3})
    in ets_unnamed.erl line 31
   8: P.1: true = erlang:register(tabler, P.1)
    in ets_unnamed.erl line 32
   9: P.2: 3 = ets:new(table, [private])
    in ets_unnamed.erl line 29
  10: P.2: true = ets:insert(3, {1,2})
    in ets_unnamed.erl line 30
  11: P.2: true = ets:insert(3, {1,3})
    in ets_unnamed.erl line 31
  12: P.3: 4 = ets:new(table, [private])
    in ets_unnamed.erl line 29
  13: P.3: true = ets:insert(4, {1,2})
    in ets_unnamed.erl line 30
  14: P.3: true = ets:insert(4, {1,3})
    in ets_unnamed.erl line 31
  15: P.3: Exception badarg raised by: erlang:register(tabler, P.3)
    in ets_unnamed.erl line 32
  16: P.3: exits abnormally ({badarg,[{erlang,register,[tabler,P.3],[32,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  17: P.3: true = ets:delete(4)
    (while exiting)
  18: P.1: exits normally
  19: P.1: true = ets:delete(2)
    (while exiting)
  20: P.2: true = erlang:register(tabler, P.2)
    in ets_unnamed.erl line 32
  21: P.2: exits normally
  22: P.2: true = ets:delete(3)
    (while exiting)
################################################################################
Interleaving #9
--------------------------------------------------------------------------------
Errors found:
* At step 19 process P.1 exited abnormally
    Reason:
      {badarg,[{erlang,register,
                       [tabler,P.1],
                       [32,
                        {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]}
    Stacktrace:
      [{erlang,register,
               [tabler,P.1],
               [32,
                {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]
--------------------------------------------------------------------------------
Event trace:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   3: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   4: P: exits normally
   5: P.1: 2 = ets:new(table, [private])
    in ets_unnamed.erl line 29
   6: P.1: true = ets:insert(2, {1,2})
    in ets_unnamed.erl line 30
   7: P.1: true = ets:insert(2, {1,3})
    in ets_unnamed.erl line 31
   8: P.2: 3 = ets:new(table, [private])
    in ets_unnamed.erl line 29
   9: P.2: true = ets:insert(3, {1,2})
    in ets_unnamed.erl line 30
  10: P.2: true = ets:insert(3, {1,3})
    in ets_unnamed.erl line 31
  11: P.3: 4 = ets:new(table, [private])
    in ets_unnamed.erl line 29
  12: P.3: true = ets:insert(4, {1,2})
    in ets_unnamed.erl line 30
  13: P.3: true = ets:insert(4, {1,3})
    in ets_unnamed.erl line 31
  14: P.2: true = erlang:register(tabler, P.2)
    in ets_unnamed.erl line 32
  15: P.2: exits normally
  16: P.2: true = ets:delete(3)
    (while exiting)
  17: P.3: true = erlang:register(tabler, P.3)
    in ets_unnamed.erl line 32
  18: P.1: Exception badarg raised by: erlang:register(tabler, P.1)
    in ets_unnamed.erl line 32
  19: P.1: exits abnormally ({badarg,[{erlang,register,[tabler,P.1],[32,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  20: P.1: true = ets:delete(2)
    (while exiting)
  21: P.3: exits normally
  22: P.3: true = ets:delete(4)
    (while exiting)
################################################################################
Interleaving #11
--------------------------------------------------------------------------------
Errors found:
* At step 19 process P.3 exited abnormally
    Reason:
      {badarg,[{erlang,register,
                       [tabler,P.3],
                       [32,
                        {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]}
    Stacktrace:
      [{erlang,register,
               [tabler,P.3],
               [32,
                {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]
--------------------------------------------------------------------------------
Event trace:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   3: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   4: P: exits normally
   5: P.1: 2 = ets:new(table, [private])
    in ets_unnamed.erl line 29
   6: P.1: true = ets:insert(2, {1,2})
    in ets_unnamed.erl line 30
   7: P.1: true = ets:insert(2, {1,3})
    in ets_unnamed.erl line 31
   8: P.2: 3 = ets:new(table, [private])
    in ets_unnamed.erl line 29
   9: P.2: true = ets:insert(3, {1,2})
    in ets_unnamed.erl line 30
  10: P.2: true = ets:insert(3, {1,3})
    in ets_unnamed.erl line 31
  11: P.3: 4 = ets:new(table, [private])
    in ets_unnamed.erl line 29
  12: P.3: true = ets:insert(4, {1,2})
    in ets_unnamed.erl line 30
  13: P.3: true = ets:insert(4, {1,3})
    in ets_unnamed.erl line 31
  14: P.2: true = erlang:register(tabler, P.2)
    in ets_unnamed.erl line 32
  15: P.2: exits normally
  16: P.2: true = ets:delete(3)
    (while exiting)
  17: P.1: true = erlang:register(tabler, P.1)
    in ets_unnamed.erl line 32
  18: P.3: Exception badarg raised by: erlang:register(tabler, P.3)
    in ets_unnamed.erl line 32
  19: P.3: exits abnormally ({badarg,[{erlang,register,[tabler,P.3],[32,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  20: P.3: true = ets:delete(4)
    (while exiting)
  21: P.1: exits normally
  22: P.1: true = ets:delete(2)
    (while exiting)
################################################################################
Interleaving #12
--------------------------------------------------------------------------------
Errors found:
* At step 16 process P.3 exited abnormally
    Reason:
      {badarg,[{erlang,register,
                       [tabler,P.3],
                       [32,
                        {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]}
    Stacktrace:
      [{erlang,register,
               [tabler,P.3],
               [32,
                {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]
* At step 19 process P.1 exited abnormally
    Reason:
      {badarg,[{erlang,register,
                       [tabler,P.1],
                       [32,
                        {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]}
    Stacktrace:
      [{erlang,register,
               [tabler,P.1],
               [32,
                {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]
--------------------------------------------------------------------------------
Event trace:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   3: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   4: P: exits normally
   5: P.1: 2 = ets:new(table, [private])
    in ets_unnamed.erl line 29
   6: P.1: true = ets:insert(2, {1,2})
    in ets_unnamed.erl line 30
   7: P.1: true = ets:insert(2, {1,3})
    in ets_unnamed.erl line 31
   8: P.2: 3 = ets:new(table, [private])
    in ets_unnamed.erl line 29
   9: P.2: true = ets:insert(3, {1,2})
    in ets_unnamed.erl line 30
  10: P.2: true = ets:insert(3, {1,3})
    in ets_unnamed.erl line 31
  11: P.3: 4 = ets:new(table, [private])
    in ets_unnamed.erl line 29
  12: P.3: true = ets:insert(4, {1,2})
    in ets_unnamed.erl line 30
  13: P.3: true = ets:insert(4, {1,3})
    in ets_unnamed.erl line 31
  14: P.2: true = erlang:register(tabler, P.2)
    in ets_unnamed.erl line 32
  15: P.3: Exception badarg raised by: erlang:register(tabler, P.3)
    in ets_unnamed.erl line 32
  16: P.3: exits abnormally ({badarg,[{erlang,register,[tabler,P.3],[32,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  17: P.3: true = ets:delete(4)
    (while exiting)
  18: P.1: Exception badarg raised by: erlang:register(tabler, P.1)
    in ets_unnamed.erl line 32
  19: P.1: exits abnormally ({badarg,[{erlang,register,[tabler,P.1],[32,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  20: P.1: true = ets:delete(2)
    (while exiting)
  21: P.2: exits normally
  22: P.2: true = ets:delete(3)
    (while exiting)
################################################################################
Interleaving #13
--------------------------------------------------------------------------------
Errors found:
* At step 16 process P.3 exited abnormally
    Reason:
      {badarg,[{erlang,register,
                       [tabler,P.3],
                       [32,
                        {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]}
    Stacktrace:
      [{erlang,register,
               [tabler,P.3],
               [32,
                {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]
--------------------------------------------------------------------------------
Event trace:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   3: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   4: P: exits normally
   5: P.1: 2 = ets:new(table, [private])
    in ets_unnamed.erl line 29
   6: P.1: true = ets:insert(2, {1,2})
    in ets_unnamed.erl line 30
   7: P.1: true = ets:insert(2, {1,3})
    in ets_unnamed.erl line 31
   8: P.2: 3 = ets:new(table, [private])
    in ets_unnamed.erl line 29
   9: P.2: true = ets:insert(3, {1,2})
    in ets_unnamed.erl line 30
  10: P.2: true = ets:insert(3, {1,3})
    in ets_unnamed.erl line 31
  11: P.3: 4 = ets:new(table, [private])
    in ets_unnamed.erl line 29
  12: P.3: true = ets:insert(4, {1,2})
    in ets_unnamed.erl line 30
  13: P.3: true = ets:insert(4, {1,3})
    in ets_unnamed.erl line 31
  14: P.2: true = erlang:register(tabler, P.2)
    in ets_unnamed.erl line 32
  15: P.3: Exception badarg raised by: erlang:register(tabler, P.3)
    in ets_unnamed.erl line 32
  16: P.3: exits abnormally ({badarg,[{erlang,register,[tabler,P.3],[32,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  17: P.3: true = ets:delete(4)
    (while exiting)
  18: P.2: exits normally
  19: P.2: true = ets:delete(3)
    (while exiting)
  20: P.1: true = erlang:register(tabler, P.1)
    in ets_unnamed.erl line 32
  21: P.1: exits normally
  22: P.1: true = ets:delete(2)
    (while exiting)
################################################################################
Interleaving #14
--------------------------------------------------------------------------------
Errors found:
* At step 16 process P.1 exited abnormally
    Reason:
      {badarg,[{erlang,register,
                       [tabler,P.1],
                       [32,
                        {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]}
    Stacktrace:
      [{erlang,register,
               [tabler,P.1],
               [32,
                {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]
--------------------------------------------------------------------------------
Event trace:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   3: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   4: P: exits normally
   5: P.1: 2 = ets:new(table, [private])
    in ets_unnamed.erl line 29
   6: P.1: true = ets:insert(2, {1,2})
    in ets_unnamed.erl line 30
   7: P.1: true = ets:insert(2, {1,3})
    in ets_unnamed.erl line 31
   8: P.2: 3 = ets:new(table, [private])
    in ets_unnamed.erl line 29
   9: P.2: true = ets:insert(3, {1,2})
    in ets_unnamed.erl line 30
  10: P.2: true = ets:insert(3, {1,3})
    in ets_unnamed.erl line 31
  11: P.3: 4 = ets:new(table, [private])
    in ets_unnamed.erl line 29
  12: P.3: true = ets:insert(4, {1,2})
    in ets_unnamed.erl line 30
  13: P.3: true = ets:insert(4, {1,3})
    in ets_unnamed.erl line 31
  14: P.2: true = erlang:register(tabler, P.2)
    in ets_unnamed.erl line 32
  15: P.1: Exception badarg raised by: erlang:register(tabler, P.1)
    in ets_unnamed.erl line 32
  16: P.1: exits abnormally ({badarg,[{erlang,register,[tabler,P.1],[32,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  17: P.1: true = ets:delete(2)
    (while exiting)
  18: P.2: exits normally
  19: P.2: true = ets:delete(3)
    (while exiting)
  20: P.3: true = erlang:register(tabler, P.3)
    in ets_unnamed.erl line 32
  21: P.3: exits normally
  22: P.3: true = ets:delete(4)
    (while exiting)
################################################################################
Interleaving #16
--------------------------------------------------------------------------------
Errors found:
* At step 19 process P.2 exited abnormally
    Reason:
      {badarg,[{erlang,register,
                       [tabler,P.2],
                       [32,
                        {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]}
    Stacktrace:
      [{erlang,register,
               [tabler,P.2],
               [32,
                {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]
--------------------------------------------------------------------------------
Event trace:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   3: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   4: P: exits normally
   5: P.1: 2 = ets:new(table, [private])
    in ets_unnamed.erl line 29
   6: P.1: true = ets:insert(2, {1,2})
    in ets_unnamed.erl line 30
   7: P.1: true = ets:insert(2, {1,3})
    in ets_unnamed.erl line 31
   8: P.2: 3 = ets:new(table, [private])
    in ets_unnamed.erl line 29
   9: P.2: true = ets:insert(3, {1,2})
    in ets_unnamed.erl line 30
  10: P.2: true = ets:insert(3, {1,3})
    in ets_unnamed.erl line 31
  11: P.3: 4 = ets:new(table, [private])
    in ets_unnamed.erl line 29
  12: P.3: true = ets:insert(4, {1,2})
    in ets_unnamed.erl line 30
  13: P.3: true = ets:insert(4, {1,3})
    in ets_unnamed.erl line 31
  14: P.3: true = erlang:register(tabler, P.3)
    in ets_unnamed.erl line 32
  15: P.3: exits normally
  16: P.3: true = ets:delete(4)
    (while exiting)
  17: P.1: true = erlang:register(tabler, P.1)
    in ets_unnamed.erl line 32
  18: P.2: Exception badarg raised by: erlang:register(tabler, P.2)
    in ets_unnamed.erl line 32
  19: P.2: exits abnormally ({badarg,[{erlang,register,[tabler,P.2],[32,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  20: P.2: true = ets:delete(3)
    (while exiting)
  21: P.1: exits normally
  22: P.1: true = ets:delete(2)
    (while exiting)
################################################################################
Interleaving #18
--------------------------------------------------------------------------------
Errors found:
* At step 19 process P.1 exited abnormally
    Reason:
      {badarg,[{erlang,register,
                       [tabler,P.1],
                       [32,
                        {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]}
    Stacktrace:
      [{erlang,register,
               [tabler,P.1],
               [32,
                {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]
--------------------------------------------------------------------------------
Event trace:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   3: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   4: P: exits normally
   5: P.1: 2 = ets:new(table, [private])
    in ets_unnamed.erl line 29
   6: P.1: true = ets:insert(2, {1,2})
    in ets_unnamed.erl line 30
   7: P.1: true = ets:insert(2, {1,3})
    in ets_unnamed.erl line 31
   8: P.2: 3 = ets:new(table, [private])
    in ets_unnamed.erl line 29
   9: P.2: true = ets:insert(3, {1,2})
    in ets_unnamed.erl line 30
  10: P.2: true = ets:insert(3, {1,3})
    in ets_unnamed.erl line 31
  11: P.3: 4 = ets:new(table, [private])
    in ets_unnamed.erl line 29
  12: P.3: true = ets:insert(4, {1,2})
    in ets_unnamed.erl line 30
  13: P.3: true = ets:insert(4, {1,3})
    in ets_unnamed.erl line 31
  14: P.3: true = erlang:register(tabler, P.3)
    in ets_unnamed.erl line 32
  15: P.3: exits normally
  16: P.3: true = ets:delete(4)
    (while exiting)
  17: P.2: true = erlang:register(tabler, P.2)
    in ets_unnamed.erl line 32
  18: P.1: Exception badarg raised by: erlang:register(tabler, P.1)
    in ets_unnamed.erl line 32
  19: P.1: exits abnormally ({badarg,[{erlang,register,[tabler,P.1],[32,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  20: P.1: true = ets:delete(2)
    (while exiting)
  21: P.2: exits normally
  22: P.2: true = ets:delete(3)
    (while exiting)
################################################################################
Interleaving #19
--------------------------------------------------------------------------------
Errors found:
* At step 16 process P.1 exited abnormally
    Reason:
      {badarg,[{erlang,register,
                       [tabler,P.1],
                       [32,
                        {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]}
    Stacktrace:
      [{erlang,register,
               [tabler,P.1],
               [32,
                {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]
* At step 19 process P.2 exited abnormally
    Reason:
      {badarg,[{erlang,register,
                       [tabler,P.2],
                       [32,
                        {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]}
    Stacktrace:
      [{erlang,register,
               [tabler,P.2],
               [32,
                {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]
--------------------------------------------------------------------------------
Event trace:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   3: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   4: P: exits normally
   5: P.1: 2 = ets:new(table, [private])
    in ets_unnamed.erl line 29
   6: P.1: true = ets:insert(2, {1,2})
    in ets_unnamed.erl line 30
   7: P.1: true = ets:insert(2, {1,3})
    in ets_unnamed.erl line 31
   8: P.2: 3 = ets:new(table, [private])
    in ets_unnamed.erl line 29
   9: P.2: true = ets:insert(3, {1,2})
    in ets_unnamed.erl line 30
  10: P.2: true = ets:insert(3, {1,3})
    in ets_unnamed.erl line 31
  11: P.3: 4 = ets:new(table, [private])
    in ets_unnamed.erl line 29
  12: P.3: true = ets:insert(4, {1,2})
    in ets_unnamed.erl line 30
  13: P.3: true = ets:insert(4, {1,3})
    in ets_unnamed.erl line 31
  14: P.3: true = erlang:register(tabler, P.3)
    in ets_unnamed.erl line 32
  15: P.1: Exception badarg raised by: erlang:register(tabler, P.1)
    in ets_unnamed.erl line 32
  16: P.1: exits abnormally ({badarg,[{erlang,register,[tabler,P.1],[32,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  17: P.1: true = ets:delete(2)
    (while exiting)
  18: P.2: Exception badarg raised by: erlang:register(tabler, P.2)
    in ets_unnamed.erl line 32
  19: P.2: exits abnormally ({badarg,[{erlang,register,[tabler,P.2],[32,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  20: P.2: true = ets:delete(3)
    (while exiting)
  21: P.3: exits normally
  22: P.3: true = ets:delete(4)
    (while exiting)
################################################################################
Interleaving #20
--------------------------------------------------------------------------------
Errors found:
* At step 16 process P.1 exited abnormally
    Reason:
      {badarg,[{erlang,register,
                       [tabler,P.1],
                       [32,
                        {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]}
    Stacktrace:
      [{erlang,register,
               [tabler,P.1],
               [32,
                {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]
--------------------------------------------------------------------------------
Event trace:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   3: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   4: P: exits normally
   5: P.1: 2 = ets:new(table, [private])
    in ets_unnamed.erl line 29
   6: P.1: true = ets:insert(2, {1,2})
    in ets_unnamed.erl line 30
   7: P.1: true = ets:insert(2, {1,3})
    in ets_unnamed.erl line 31
   8: P.2: 3 = ets:new(table, [private])
    in ets_unnamed.erl line 29
   9: P.2: true = ets:insert(3, {1,2})
    in ets_unnamed.erl line 30
  10: P.2: true = ets:insert(3, {1,3})
    in ets_unnamed.erl line 31
  11: P.3: 4 = ets:new(table, [private])
    in ets_unnamed.erl line 29
  12: P.3: true = ets:insert(4, {1,2})
    in ets_unnamed.erl line 30
  13: P.3: true = ets:insert(4, {1,3})
    in ets_unnamed.erl line 31
  14: P.3: true = erlang:register(tabler, P.3)
    in ets_unnamed.erl line 32
  15: P.1: Exception badarg raised by: erlang:register(tabler, P.1)
    in ets_unnamed.erl line 32
  16: P.1: exits abnormally ({badarg,[{erlang,register,[tabler,P.1],[32,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  17: P.1: true = ets:delete(2)
    (while exiting)
  18: P.3: exits normally
  19: P.3: true = ets:delete(4)
    (while exiting)
  20: P.2: true = erlang:register(tabler, P.2)
    in ets_unnamed.erl line 32
  21: P.2: exits normally
  22: P.2: true = ets:delete(3)
    (while exiting)
################################################################################
Interleaving #21
--------------------------------------------------------------------------------
Errors found:
* At step 16 process P.2 exited abnormally
    Reason:
      {badarg,[{erlang,register,
                       [tabler,P.2],
                       [32,
                        {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]}
    Stacktrace:
      [{erlang,register,
               [tabler,P.2],
               [32,
                {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_unnamed.erl"}]}]
--------------------------------------------------------------------------------
Event trace:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   3: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_unnamed.'-test3/0-fun-0-'.0>,[]])
    in erlang.erl line 2603
   4: P: exits normally
   5: P.1: 2 = ets:new(table, [private])
    in ets_unnamed.erl line 29
   6: P.1: true = ets:insert(2, {1,2})
    in ets_unnamed.erl line 30
   7: P.1: true = ets:insert(2, {1,3})
    in ets_unnamed.erl line 31
   8: P.2: 3 = ets:new(table, [private])
    in ets_unnamed.erl line 29
   9: P.2: true = ets:insert(3, {1,2})
    in ets_unnamed.erl line 30
  10: P.2: true = ets:insert(3, {1,3})
    in ets_unnamed.erl line 31
  11: P.3: 4 = ets:new(table, [private])
    in ets_unnamed.erl line 29
  12: P.3: true = ets:insert(4, {1,2})
    in ets_unnamed.erl line 30
  13: P.3: true = ets:insert(4, {1,3})
    in ets_unnamed.erl line 31
  14: P.3: true = erlang:register(tabler, P.3)
    in ets_unnamed.erl line 32
  15: P.2: Exception badarg raised by: erlang:register(tabler, P.2)
    in ets_unnamed.erl line 32
  16: P.2: exits abnormally ({badarg,[{erlang,register,[tabler,P.2],[32,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  17: P.2: true = ets:delete(3)
    (while exiting)
  18: P.3: exits normally
  19: P.3: true = ets:delete(4)
    (while exiting)
  20: P.1: true = erlang:register(tabler, P.1)
    in ets_unnamed.erl line 32
  21: P.1: exits normally
  22: P.1: true = ets:delete(2)
    (while exiting)
################################################################################
Exploration completed!
################################################################################
Info:
--------------------------------------------------------------------------------
Instrumented ets_unnamed
Instrumented io_lib
Instrumented gen_server
Instrumented erlang
You can see pairs of racing instructions (in the report and --graph) with '--show_races true'
Continuing after error (-k)

################################################################################
Done at 24 Nov 2016 14:18:14 (Exit status: error)
  Summary: 15 errors, 21/21 interleavings explored
