################################################################################
Concuerror started with options:
  [{'after-timeout',infinite},
   {bound,-1},
   {distributed,true},
   {files,["/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_new_failure_2.erl"]},
   {'light-dpor',false},
   {symbolic,true},
   {target,{ets_new_failure_2,ets_new_failure_2,[]}},
   {verbose,0},
   {wait,5000}]
################################################################################
Erroneous interleaving 1:
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_new_failure_2.erl line 22
    P.1 in ets_new_failure_2.erl line 14
* At step 8 process P.2 exited abnormally
    Reason:
      {badarg,
          [{ets,new,
               [table,[named_table,public]],
               [12,
                {file,
                    "/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_new_failure_2.erl"}]},
           {ets_new_failure_2,'-ets_new_failure_2/0-fun-0-',1,
               [{file,
                    "/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_new_failure_2.erl"},
                {line,12}]}]}
    Stacktrace:
      [{ets,new,
            [table,[named_table,public]],
            [12,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_new_failure_2.erl"}]},
       {ets_new_failure_2,'-ets_new_failure_2/0-fun-0-',1,
                          [{file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_new_failure_2.erl"},
                           {line,12}]}]
--------------------------------------------------------------------------------
Interleaving info:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_new_failure_2.0.1511511>,[]])
    in erlang.erl line 2188
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_new_failure_2.0.1511511>,[]])
    in erlang.erl line 2188
   3: P.1: table = ets:new(table, [named_table,public])
    in ets_new_failure_2.erl line 12
   4: P.1: ok = P ! ok
    in ets_new_failure_2.erl line 13
   5: Message (ok) from P.1 reaches P
   6: P: receives message (ok)
    in ets_new_failure_2.erl line 20
   7: P.2: Exception badarg raised by: ets:new(table, [named_table,public])
    in ets_new_failure_2.erl line 12
   8: P.2: exits abnormally ({badarg,[{ets,new,[table,[named_table,public]],[12,{file,[47,104,111,109,101,47,115,116,97,118,114,111,115,47,103,105,116,47,67,111,110,99,117,101,114,114,111,114,47,116,101,115,116,115,47,115,117,105,116,101,115,47,98,97,115,105,99,95,116,101,115,116,115,47,115,114,99,47,101,116,115,95,110,101,119,95,102,97,105,108,117,114,101,95,50,46,101,114,108]}]},{ets_new_failure_2,'-ets_new_failure_2/0-fun-0-',1,[{file,[47,104,111,109,101,47,115,116,97,118,114,111,115,47,103,105,116,47,67,111,110,99,117,101,114,114,111,114,47,116,101,115,116,115,47,115,117,105,116,101,115,47,98,97,115,105,99,95,116,101,115,116,115,47,115,114,99,47,101,116,115,95,110,101,119,95,102,97,105,108,117,114,101,95,50,46,101,114,108]},{line,12}]}]})
################################################################################
Erroneous interleaving 2:
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_new_failure_2.erl line 22
    P.2 in ets_new_failure_2.erl line 14
* At step 5 process P.1 exited abnormally
    Reason:
      {badarg,
          [{ets,new,
               [table,[named_table,public]],
               [12,
                {file,
                    "/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_new_failure_2.erl"}]},
           {ets_new_failure_2,'-ets_new_failure_2/0-fun-0-',1,
               [{file,
                    "/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_new_failure_2.erl"},
                {line,12}]}]}
    Stacktrace:
      [{ets,new,
            [table,[named_table,public]],
            [12,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_new_failure_2.erl"}]},
       {ets_new_failure_2,'-ets_new_failure_2/0-fun-0-',1,
                          [{file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_new_failure_2.erl"},
                           {line,12}]}]
--------------------------------------------------------------------------------
Interleaving info:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_new_failure_2.0.1511511>,[]])
    in erlang.erl line 2188
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_new_failure_2.0.1511511>,[]])
    in erlang.erl line 2188
   3: P.2: table = ets:new(table, [named_table,public])
    in ets_new_failure_2.erl line 12
   4: P.1: Exception badarg raised by: ets:new(table, [named_table,public])
    in ets_new_failure_2.erl line 12
   5: P.1: exits abnormally ({badarg,[{ets,new,[table,[named_table,public]],[12,{file,[47,104,111,109,101,47,115,116,97,118,114,111,115,47,103,105,116,47,67,111,110,99,117,101,114,114,111,114,47,116,101,115,116,115,47,115,117,105,116,101,115,47,98,97,115,105,99,95,116,101,115,116,115,47,115,114,99,47,101,116,115,95,110,101,119,95,102,97,105,108,117,114,101,95,50,46,101,114,108]}]},{ets_new_failure_2,'-ets_new_failure_2/0-fun-0-',1,[{file,[47,104,111,109,101,47,115,116,97,118,114,111,115,47,103,105,116,47,67,111,110,99,117,101,114,114,111,114,47,116,101,115,116,115,47,115,117,105,116,101,115,47,98,97,115,105,99,95,116,101,115,116,115,47,115,114,99,47,101,116,115,95,110,101,119,95,102,97,105,108,117,114,101,95,50,46,101,114,108]},{line,12}]}]})
   6: P.2: ok = P ! ok
    in ets_new_failure_2.erl line 13
   7: Message (ok) from P.2 reaches P
   8: P: receives message (ok)
    in ets_new_failure_2.erl line 20
################################################################################
Done! (Exit status: completed)
  Summary: 2 errors, 2/2 interleavings explored
