Concuerror 0.17 (d20441c) started at 24 Nov 2016 14:38:40.
 Options:
  [{after_timeout,infinity},
   {assertions_only,false},
   {assume_racing,false},
   {depth_bound,500},
   {disable_sleep_sets,false},
   {dpor,optimal},
   {entry_point,{ets_exceptions,test,[]}},
   {files,["/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_exceptions.erl"]},
   {ignore_error,[]},
   {instant_delivery,true},
   {interleaving_bound,infinity},
   {keep_going,true},
   {non_racing_system,[]},
   {print_depth,20},
   {scheduling,round_robin},
   {scheduling_bound_type,none},
   {show_races,false},
   {strict_scheduling,false},
   {symbolic_names,true},
   {timeout,infinity},
   {treat_as_normal,[]}]
################################################################################
Interleaving #1
--------------------------------------------------------------------------------
Errors found:
* At step 8 process P.1 exited abnormally
    Reason:
      {badarg,[{ets,insert,
                    [table,{key,2}],
                    [18,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_exceptions.erl"}]}]}
    Stacktrace:
      [{ets,insert,
            [table,{key,2}],
            [18,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_exceptions.erl"}]}]
* At step 10 process P.2 exited abnormally
    Reason:
      {badarg,[{ets,insert,
                    [table,{key,1}],
                    [18,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_exceptions.erl"}]}]}
    Stacktrace:
      [{ets,insert,
            [table,{key,1}],
            [18,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_exceptions.erl"}]}]
--------------------------------------------------------------------------------
Event trace:
   1: P: table = ets:new(table, [public,named_table])
    in ets_exceptions.erl line 12
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_exceptions.'-chain/1-fun-0-'.0>,[]])
    in erlang.erl line 2603
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_exceptions.'-chain/1-fun-0-'.0>,[]])
    in erlang.erl line 2603
   4: P: [] = ets:lookup(table, key)
    in ets_exceptions.erl line 14
   5: P: exits normally
   6: P: true = ets:delete(table)
    (while exiting)
   7: P.1: Exception badarg raised by: ets:insert(table, {key,2})
    in ets_exceptions.erl line 18
   8: P.1: exits abnormally ({badarg,[{ets,insert,[table,{key,2}],[18,{file,[47,104,111,109,101,47,115,116|...]}]}]})
   9: P.2: Exception badarg raised by: ets:insert(table, {key,1})
    in ets_exceptions.erl line 18
  10: P.2: exits abnormally ({badarg,[{ets,insert,[table,{key,1}],[18,{file,[47,104,111,109,101,47,115,116|...]}]}]})
################################################################################
Interleaving #3
--------------------------------------------------------------------------------
Errors found:
* At step 10 process P.2 exited abnormally
    Reason:
      {badarg,[{ets,insert,
                    [table,{key,1}],
                    [18,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_exceptions.erl"}]}]}
    Stacktrace:
      [{ets,insert,
            [table,{key,1}],
            [18,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_exceptions.erl"}]}]
--------------------------------------------------------------------------------
Event trace:
   1: P: table = ets:new(table, [public,named_table])
    in ets_exceptions.erl line 12
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_exceptions.'-chain/1-fun-0-'.0>,[]])
    in erlang.erl line 2603
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_exceptions.'-chain/1-fun-0-'.0>,[]])
    in erlang.erl line 2603
   4: P: [] = ets:lookup(table, key)
    in ets_exceptions.erl line 14
   5: P: exits normally
   6: P.1: true = ets:insert(table, {key,2})
    in ets_exceptions.erl line 18
   7: P.1: exits normally
   8: P: true = ets:delete(table)
    (while exiting)
   9: P.2: Exception badarg raised by: ets:insert(table, {key,1})
    in ets_exceptions.erl line 18
  10: P.2: exits abnormally ({badarg,[{ets,insert,[table,{key,1}],[18,{file,[47,104,111,109,101,47,115,116|...]}]}]})
################################################################################
Interleaving #4
--------------------------------------------------------------------------------
Errors found:
* At step 10 process P.1 exited abnormally
    Reason:
      {badarg,[{ets,insert,
                    [table,{key,2}],
                    [18,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_exceptions.erl"}]}]}
    Stacktrace:
      [{ets,insert,
            [table,{key,2}],
            [18,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_exceptions.erl"}]}]
--------------------------------------------------------------------------------
Event trace:
   1: P: table = ets:new(table, [public,named_table])
    in ets_exceptions.erl line 12
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_exceptions.'-chain/1-fun-0-'.0>,[]])
    in erlang.erl line 2603
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_exceptions.'-chain/1-fun-0-'.0>,[]])
    in erlang.erl line 2603
   4: P: [] = ets:lookup(table, key)
    in ets_exceptions.erl line 14
   5: P: exits normally
   6: P.2: true = ets:insert(table, {key,1})
    in ets_exceptions.erl line 18
   7: P.2: exits normally
   8: P: true = ets:delete(table)
    (while exiting)
   9: P.1: Exception badarg raised by: ets:insert(table, {key,2})
    in ets_exceptions.erl line 18
  10: P.1: exits abnormally ({badarg,[{ets,insert,[table,{key,2}],[18,{file,[47,104,111,109,101,47,115,116|...]}]}]})
################################################################################
Interleaving #7
--------------------------------------------------------------------------------
Errors found:
* At step 7 process P exited abnormally
    Reason:
      {{badmatch,false},
       [{ets_exceptions,test,1,
                        [{file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_exceptions.erl"},
                         {line,14}]}]}
    Stacktrace:
      [{ets_exceptions,test,1,
                       [{file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_exceptions.erl"},
                        {line,14}]}]
* At step 10 process P.2 exited abnormally
    Reason:
      {badarg,[{ets,insert,
                    [table,{key,1}],
                    [18,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_exceptions.erl"}]}]}
    Stacktrace:
      [{ets,insert,
            [table,{key,1}],
            [18,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_exceptions.erl"}]}]
--------------------------------------------------------------------------------
Event trace:
   1: P: table = ets:new(table, [public,named_table])
    in ets_exceptions.erl line 12
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_exceptions.'-chain/1-fun-0-'.0>,[]])
    in erlang.erl line 2603
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_exceptions.'-chain/1-fun-0-'.0>,[]])
    in erlang.erl line 2603
   4: P.1: true = ets:insert(table, {key,2})
    in ets_exceptions.erl line 18
   5: P.1: exits normally
   6: P: [{key,2}] = ets:lookup(table, key)
    in ets_exceptions.erl line 14
   7: P: exits abnormally ({{badmatch,false},[{ets_exceptions,test,1,[{file,[47,104,111,109,101,47,115,116,97|...]},{line,14}]}]})
   8: P: true = ets:delete(table)
    (while exiting)
   9: P.2: Exception badarg raised by: ets:insert(table, {key,1})
    in ets_exceptions.erl line 18
  10: P.2: exits abnormally ({badarg,[{ets,insert,[table,{key,1}],[18,{file,[47,104,111,109,101,47,115,116|...]}]}]})
################################################################################
Interleaving #8
--------------------------------------------------------------------------------
Errors found:
* At step 7 process P exited abnormally
    Reason:
      {{badmatch,false},
       [{ets_exceptions,test,1,
                        [{file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_exceptions.erl"},
                         {line,14}]}]}
    Stacktrace:
      [{ets_exceptions,test,1,
                       [{file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_exceptions.erl"},
                        {line,14}]}]
--------------------------------------------------------------------------------
Event trace:
   1: P: table = ets:new(table, [public,named_table])
    in ets_exceptions.erl line 12
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_exceptions.'-chain/1-fun-0-'.0>,[]])
    in erlang.erl line 2603
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_exceptions.'-chain/1-fun-0-'.0>,[]])
    in erlang.erl line 2603
   4: P.1: true = ets:insert(table, {key,2})
    in ets_exceptions.erl line 18
   5: P.1: exits normally
   6: P: [{key,2}] = ets:lookup(table, key)
    in ets_exceptions.erl line 14
   7: P: exits abnormally ({{badmatch,false},[{ets_exceptions,test,1,[{file,[47,104,111,109,101,47,115,116,97|...]},{line,14}]}]})
   8: P.2: true = ets:insert(table, {key,1})
    in ets_exceptions.erl line 18
   9: P.2: exits normally
  10: P: true = ets:delete(table)
    (while exiting)
################################################################################
Interleaving #9
--------------------------------------------------------------------------------
Errors found:
* At step 10 process P.1 exited abnormally
    Reason:
      {badarg,[{ets,insert,
                    [table,{key,2}],
                    [18,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_exceptions.erl"}]}]}
    Stacktrace:
      [{ets,insert,
            [table,{key,2}],
            [18,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_exceptions.erl"}]}]
--------------------------------------------------------------------------------
Event trace:
   1: P: table = ets:new(table, [public,named_table])
    in ets_exceptions.erl line 12
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_exceptions.'-chain/1-fun-0-'.0>,[]])
    in erlang.erl line 2603
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_exceptions.'-chain/1-fun-0-'.0>,[]])
    in erlang.erl line 2603
   4: P.2: true = ets:insert(table, {key,1})
    in ets_exceptions.erl line 18
   5: P.2: exits normally
   6: P: [{key,1}] = ets:lookup(table, key)
    in ets_exceptions.erl line 14
   7: P: exits normally
   8: P: true = ets:delete(table)
    (while exiting)
   9: P.1: Exception badarg raised by: ets:insert(table, {key,2})
    in ets_exceptions.erl line 18
  10: P.1: exits abnormally ({badarg,[{ets,insert,[table,{key,2}],[18,{file,[47,104,111,109,101,47,115,116|...]}]}]})
################################################################################
Interleaving #11
--------------------------------------------------------------------------------
Errors found:
* At step 9 process P exited abnormally
    Reason:
      {{badmatch,false},
       [{ets_exceptions,test,1,
                        [{file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_exceptions.erl"},
                         {line,14}]}]}
    Stacktrace:
      [{ets_exceptions,test,1,
                       [{file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_exceptions.erl"},
                        {line,14}]}]
--------------------------------------------------------------------------------
Event trace:
   1: P: table = ets:new(table, [public,named_table])
    in ets_exceptions.erl line 12
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_exceptions.'-chain/1-fun-0-'.0>,[]])
    in erlang.erl line 2603
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_exceptions.'-chain/1-fun-0-'.0>,[]])
    in erlang.erl line 2603
   4: P.2: true = ets:insert(table, {key,1})
    in ets_exceptions.erl line 18
   5: P.2: exits normally
   6: P.1: true = ets:insert(table, {key,2})
    in ets_exceptions.erl line 18
   7: P.1: exits normally
   8: P: [{key,2}] = ets:lookup(table, key)
    in ets_exceptions.erl line 14
   9: P: exits abnormally ({{badmatch,false},[{ets_exceptions,test,1,[{file,[47,104,111,109,101,47,115,116,97|...]},{line,14}]}]})
  10: P: true = ets:delete(table)
    (while exiting)
################################################################################
Exploration completed!
################################################################################
Info:
--------------------------------------------------------------------------------
Instrumented ets_exceptions
Instrumented io_lib
Instrumented gen_server
Instrumented erlang
You can see pairs of racing instructions (in the report and --graph) with '--show_races true'
Continuing after error (-k)

################################################################################
Done at 24 Nov 2016 14:38:40 (Exit status: error)
  Summary: 7 errors, 11/11 interleavings explored
