Concuerror v0.17 ('9e3f818') started at 14 Sep 2017 14:18:47
 Options:
  [{after_timeout,infinity},
   {assertions_only,false},
   {assume_racing,false},
   {depth_bound,500},
   {disable_sleep_sets,false},
   {dpor,optimal},
   {entry_point,{trigger_the_after,trigger_the_after,[]}},
   {exclude_module,[]},
   {files,["/home/stavros/git/Concuerror/tests/suites/basic_tests/src/trigger_the_after.erl"]},
   {ignore_error,[]},
   {instant_delivery,true},
   {interleaving_bound,infinity},
   {keep_going,true},
   {non_racing_system,[]},
   {print_depth,20},
   {quiet,true},
   {scheduling,round_robin},
   {scheduling_bound_type,none},
   {show_races,false},
   {strict_scheduling,false},
   {symbolic_names,true},
   {timeout,infinity},
   {treat_as_normal,[]},
   {use_receive_patterns,true}]
################################################################################
Interleaving #1
--------------------------------------------------------------------------------
Errors found:
* At step 4 process P exited abnormally
    Reason:
      {error,
          [{trigger_the_after,trigger_the_after,0,
               [{file,
                    "/home/stavros/git/Concuerror/tests/suites/basic_tests/src/trigger_the_after.erl"},
                {line,12}]}]}
    Stacktrace:
      [{trigger_the_after,trigger_the_after,0,
                          [{file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/trigger_the_after.erl"},
                           {line,12}]}]
* At step 11 process P.1 exited abnormally
    Reason:
      {{nocatch,both},
       [{trigger_the_after,receive_two,0,
                           [{file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/trigger_the_after.erl"},
                            {line,18}]}]}
    Stacktrace:
      [{trigger_the_after,receive_two,0,
                          [{file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/trigger_the_after.erl"},
                           {line,18}]}]
--------------------------------------------------------------------------------
Event trace:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<trigger_the_after.'-trigger_the_after/0-fun-0-'.0>,[]])
    in erlang.erl line 2673
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<trigger_the_after.'-sender/2-fun-0-'.0>,[]])
    in erlang.erl line 2673
   3: P: P.3 = erlang:spawn(erlang, apply, [#Fun<trigger_the_after.'-sender/2-fun-0-'.0>,[]])
    in erlang.erl line 2673
   4: P: exits abnormally ({error,[{trigger_the_after,trigger_the_after,0,[{file,[47,104,111,109,101,47,115,116,97|...]},{line,12}]}]})
   5: P.2: two = P.1 ! two
    in trigger_the_after.erl line 25
   6: P.2: exits normally
   7: P.3: one = P.1 ! one
    in trigger_the_after.erl line 25
   8: P.3: exits normally
   9: P.1: receives message (one)
    in trigger_the_after.erl line 15
  10: P.1: receives message (two)
    in trigger_the_after.erl line 17
  11: P.1: exits abnormally ({{nocatch,both},[{trigger_the_after,receive_two,0,[{file,[47,104,111,109,101,47,115,116,97|...]},{line,18}]}]})
################################################################################
Interleaving #2
--------------------------------------------------------------------------------
Errors found:
* At step 4 process P exited abnormally
    Reason:
      {error,
          [{trigger_the_after,trigger_the_after,0,
               [{file,
                    "/home/stavros/git/Concuerror/tests/suites/basic_tests/src/trigger_the_after.erl"},
                {line,12}]}]}
    Stacktrace:
      [{trigger_the_after,trigger_the_after,0,
                          [{file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/trigger_the_after.erl"},
                           {line,12}]}]
* At step 9 process P.1 exited abnormally
    Reason:
      {{nocatch,one},
       [{trigger_the_after,receive_two,0,
                           [{file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/trigger_the_after.erl"},
                            {line,20}]}]}
    Stacktrace:
      [{trigger_the_after,receive_two,0,
                          [{file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/trigger_the_after.erl"},
                           {line,20}]}]
--------------------------------------------------------------------------------
Event trace:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<trigger_the_after.'-trigger_the_after/0-fun-0-'.0>,[]])
    in erlang.erl line 2673
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<trigger_the_after.'-sender/2-fun-0-'.0>,[]])
    in erlang.erl line 2673
   3: P: P.3 = erlang:spawn(erlang, apply, [#Fun<trigger_the_after.'-sender/2-fun-0-'.0>,[]])
    in erlang.erl line 2673
   4: P: exits abnormally ({error,[{trigger_the_after,trigger_the_after,0,[{file,[47,104,111,109,101,47,115,116,97|...]},{line,12}]}]})
   5: P.3: one = P.1 ! one
    in trigger_the_after.erl line 25
   6: P.3: exits normally
   7: P.1: receives message (one)
    in trigger_the_after.erl line 15
   8: P.1: receive timeout expired after 100 ms
    in trigger_the_after.erl line 17
   9: P.1: exits abnormally ({{nocatch,one},[{trigger_the_after,receive_two,0,[{file,[47,104,111,109,101,47,115,116,97|...]},{line,20}]}]})
  10: P.2: two = P.1 ! two
    in trigger_the_after.erl line 25
  11: P.2: exits normally
################################################################################
Exploration completed!
################################################################################
Tips:
--------------------------------------------------------------------------------
Increase '--print_depth' if output/graph contains "...".

################################################################################
Info:
--------------------------------------------------------------------------------
Instrumented & loaded module trigger_the_after
Automatically instrumented module io_lib
Automatically instrumented module gen_server
Automatically instrumented module erlang
You can see pairs of racing instructions (in the report and '--graph') with '--show_races true'
Continuing after error (-k)

################################################################################
Done at 14 Sep 2017 14:18:48 (Exit status: error)
  Summary: 2 errors, 2/2 interleavings explored
